'use strict';

const fs = require('fs-extra');
const path = require('path');
const { logInfo, logSuccess } = require('./logger');
const { installDevDependency } = require('./packageManager');

const SONAR_PROPS_FILE = 'sonar-project.properties';
const DEFAULT_SONAR_HOST = process.env.SONAR_HOST_URL || 'http://34.93.109.104:9000';
const DEFAULT_SONAR_TOKEN = process.env.SONAR_TOKEN || 'sqa_e42cc149df0b02a3b90e7de5525001608c4d23a4';

/**
 * Attempts to auto-create the SonarQube project via REST API.
 * Skips gracefully if server unreachable — never blocks installation.
 */
async function ensureProjectExists(projectKey, projectName, hostUrl, token) {
  if (!token) {
    logInfo('SONAR_TOKEN not set — skipping auto project creation.');
    return;
  }

  let parsedHost;
  try { parsedHost = new URL(hostUrl); }
  catch { logInfo(`Invalid SonarQube URL "${hostUrl}" — skipping.`); return; }

  const TIMEOUT_MS = 3000;
  const http = parsedHost.protocol === 'https:' ? require('https') : require('http');

  const req = new Promise((resolve) => {
    const auth = Buffer.from(`${token}:`).toString('base64');
    const postData = `name=${encodeURIComponent(projectName)}&project=${encodeURIComponent(projectKey)}`;

    const r = http.request({
      hostname: parsedHost.hostname,
      port: parsedHost.port || (parsedHost.protocol === 'https:' ? 443 : 80),
      path: '/api/projects/create',
      method: 'POST',
      headers: { Authorization: `Basic ${auth}`, 'Content-Type': 'application/x-www-form-urlencoded', 'Content-Length': Buffer.byteLength(postData) },
      timeout: TIMEOUT_MS,
    }, (res) => {
      let data = '';
      res.on('data', c => data += c);
      res.on('end', () => {
        if ([200, 201].includes(res.statusCode)) logSuccess(`SonarQube project "${projectKey}" created.`);
        else if (res.statusCode === 400 && data.includes('already exists')) logInfo(`SonarQube project "${projectKey}" already exists.`);
        else logInfo(`SonarQube responded ${res.statusCode} — continuing.`);
        resolve();
      });
    });
    r.on('error', () => { logInfo('SonarQube unreachable — skipping.'); resolve(); });
    r.on('timeout', () => { r.destroy(); logInfo('SonarQube timed out — skipping.'); resolve(); });
    r.write(postData);
    r.end();
  });

  return Promise.race([req, new Promise(r => setTimeout(r, TIMEOUT_MS + 1000))]);
}

exports.installSonarScanner = async () => {
  logInfo('Installing sonarqube-scanner...');
  await installDevDependency('sonarqube-scanner');
  logSuccess('sonarqube-scanner installed.');
};

exports.setupSonarProperties = async () => {
  const propsPath = path.join(process.cwd(), SONAR_PROPS_FILE);

  // Check if properties file already exists and is "valid" (not placeholders)
  if (await fs.pathExists(propsPath)) {
    const existingContent = await fs.readFile(propsPath, 'utf8');
    const isDefaultToken = existingContent.includes('sonar.login=REPLACE_WITH_YOUR_TOKEN') || 
                           existingContent.includes(`sonar.login=${DEFAULT_SONAR_TOKEN}`);
    const isDefaultHost = existingContent.includes(`sonar.host.url=${DEFAULT_SONAR_HOST}`);

    if (!isDefaultToken || !isDefaultHost) {
      logInfo(`${SONAR_PROPS_FILE} already customized — skipping.`);
      return;
    }
    logInfo(`${SONAR_PROPS_FILE} using defaults — overwriting with latest template.`);
  }

  let projectKey = 'my-project';
  let projectName = 'My Project';
  const pkgPath = path.join(process.cwd(), 'package.json');
  if (await fs.pathExists(pkgPath)) {
    const pkg = await fs.readJSON(pkgPath);
    if (pkg.name) {
      projectKey = pkg.name.replace(/[^a-zA-Z0-9_\-.:]/g, '_');
      projectName = pkg.name;
    }
  }

  await ensureProjectExists(projectKey, projectName, DEFAULT_SONAR_HOST, DEFAULT_SONAR_TOKEN);

  await fs.writeFile(propsPath, `# SonarQube configuration — auto-generated by cs-setup
# Set sonar.host.url and sonar.token before running analysis.
# Tip: export SONAR_HOST_URL and SONAR_TOKEN as environment variables
#      so they are never committed to git.
sonar.host.url=${DEFAULT_SONAR_HOST}
sonar.login=${DEFAULT_SONAR_TOKEN || 'REPLACE_WITH_YOUR_TOKEN'}
sonar.projectKey=${projectKey}
sonar.projectName=${projectName}
sonar.projectVersion=1.0
sonar.sources=.
sonar.sourceEncoding=UTF-8
sonar.exclusions=node_modules/**,dist/**,build/**,coverage/**,.husky/**,.tools/**
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.qualitygate.wait=true

`);

  logSuccess(`Created ${propsPath}`);
  logInfo('Edit sonar.host.url and sonar.login (or set as env vars).');
};